config/routes.rb
Ranker::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  resources :problems do
    member do
      put 'questions'
      get 'copy'
    end
    resources :questions, :only => [ :create ]
    resources :solutions, :only => [ :new, :create ]
  end
  resources :solutions, :except => [ :index, :new, :create ] do
    member do
      put 'answers'
    end
    resources :answers, :only => [ :create ]
  end
  resources :answers, :only => [ :update ]
  resources :questions, :only => [ :update, :destroy ]

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

  match '/error', :to => 'pages#error', :as => 'error'
  match '*a', :to => 'pages#error'

end

app/views/shared/_answer_fields.html.erb
<li class="answer">
  <span class="question_text">
    <%= "#{answer.question.position}) #{answer.question.text}" %>
  </span>
  <span class="information">
    <div class="rating round_top">
      <%= f.label :rating %>:
      <%= f.radio_button :rating, 1 %>1
      <%= f.radio_button :rating, 2 %>2
      <%= f.radio_button :rating, 3 %>3
      <%= f.radio_button :rating, 4 %>4
      <%= f.radio_button :rating, 5 %>5
    </div>
    <!-- TODO - need to be able to hide/show comments: default hide unless there is a value in there -->
    <div id='<%= "comment_#{answer.id}" %>' class="comment" <% if answer.comment.blank? %>style="display:none"<% end %>>
      <%= f.text_area :comment %>
    </div>
    <div id='<%= "toggle_comment_#{answer.id}" %>' class="toggle_comment round_bottom">
       <% if answer.comment.blank? %>
          Show Comment
       <% else %>
          Hide Comment
       <% end %>
    </div>
  </span>
  <script type="text/javascript">
    $('#<%= "toggle_comment_#{answer.id}" %>').click(function() {
      $('#<%= "comment_#{answer.id}" %>').slideToggle('slow', function() {
        // Animation complete.
        var $comment_span = $('#<%= "toggle_comment_#{answer.id}" %>');

        if ($comment_span.text().trim() == "Hide Comment") {
          $comment_span.text("Show Comment");
        } else {
          $comment_span.text("Hide Comment");
        }
      });
    });
  </script>
  <%= f.hidden_field :question_id %>
  <div class="clear"></div>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
	<h2><%= pluralize(object.errors.count, "error") %>
	  prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
	<p>There were problems with the following fields:</p>
	<ul>
	<% object.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
	</ul>
  </div>
<% end %>

app/views/shared/_problem_item.html.erb
<li>
  <div id='<%= "problem_#{problem_item.id}" %>' class="no_margin problem round">
    <div class="information">
    <h2>
      <%= link_to problem_item.name, problem_item %>&nbsp;<%= link_to "(edit)", edit_problem_path(problem_item), :class => "edit_text" %>
    </h2>
    <!-- TODO - need to deal with wrapping long comments -->
    <h3 class="problem_comment">
      <%= simple_format(problem_item.comment) %>
    </h3>
    </div>
  </div>
  <div class="solutions">
    <% unless problem_item.solutions.empty? %>
      <ul id='<%= "solutions_#{problem_item.id}" %>'>
        <%= render :partial => 'shared/problem_solution_item', :collection => problem_item.solutions %>
      </ul>
    <% end %>
      <ul>
        <li class="problem_solution round_bottom hide_solutions">
          <span class="left">
            <%= link_to "New Solution?", new_problem_solution_path(problem_item) %>
          </span>
          <span class="right" id='<%= "toggle_solutions_#{problem_item.id}" %>'>
            Hide Solutions
          </span>
          <div class="clear"/>
          <script type="text/javascript">
            $('#<%= "toggle_solutions_#{problem_item.id}" %>').click(function() {
              $('#<%= "solutions_#{problem_item.id}" %>').slideToggle('normal', function() {
                // Animation complete.
                var $solution_span = $('#<%= "toggle_solutions_#{problem_item.id}" %>');

                if ($solution_span.text().trim() == "Hide Solutions") {
                  $solution_span.text("Show Solutions");
                } else {
                  $solution_span.text("Hide Solutions");
                }
              });
            });
          </script>
        </li>
      </ul>
  </div>
</li>

app/views/shared/_problem_solution_item.html.erb
<li id='<%= "solution_#{problem_solution_item.id}" %>' class="problem_solution">
  <div class="information no_margin">
      <span class="ranking">
        <h3>
        <% if problem_solution_item.completed %>
          <%= number_to_percentage(problem_solution_item.match_decimal * 100, :precision => 1) %>
        <% else %>
          INC
        <% end %>
        </h3>
      </span>
      <span class="name">
        <h3>
          <%= link_to problem_solution_item.name, problem_solution_item %>
        </h3>
      </span>
  </div>
</li>

app/views/shared/_problems.html.erb
<% unless @problems.empty? %>
  <ul class="problems" summary="User problems">
	<%= render :partial => 'shared/problem_item', :collection => @problems %>
  </ul>
<% end %>