config/routes.rb
Ranker::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  resources :problems do
    member do
      put 'questions'
      get 'copy'
    end
    resources :questions, :only => [ :create ]
    resources :solutions, :only => [ :new, :create ]
  end
  resources :solutions, :except => [ :index, :new, :create ] do
    member do
      put 'answers'
    end
    resources :answers, :only => [ :create ]
  end
  resources :answers, :only => [ :update ]
  resources :questions, :only => [ :update, :destroy ]

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

  match '/error', :to => 'pages#error', :as => 'error'
  match '*a', :to => 'pages#error'

end

app/views/pages/about.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
  <li class="active">About</li>
</ul>

<h1>About</h1>
<p>This website's original purpose was to help provide a way to help medical students rank their residency choices based on a set of questions.</p>

app/views/pages/contact.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
  <li class="active">Contact</li>
</ul>

<h1>Contact</h1>
<p>If you have any questions or suggestions, please send an email to admin[at]residencyranker[dot]com</p>

app/views/pages/error.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
  <li class="active">Error</li>
</ul>

<h1>Page not found</h1>
<p>The page you were looking for does not exist.</p>

app/views/pages/help.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
  <li class="active">Help</li>
</ul>

<h1>Help</h1>
<p>Residency Ranker was originally created to allow medical students to scientifically determine their rank list based on a series of questions that they decide upon. The user gets the chance to rate on a scale of 1 to 5 how important each question is, and then rates each Program on how well it matches the critiera.</p>

app/views/pages/home.html.erb
<ul class="breadcrumb">
  <li class="active">Home</li>
</ul>

<% if user_signed_in? %>
  <div class="main">
    <%= link_to "New Problem?", new_problem_path, :class => "btn right primary template-btn" %>
    <%= link_to "Start with Residency template!", copy_problem_path(1), :class => "btn right success template-btn" %>
    <div class="clear"></div>
    <%= render 'shared/problems' %>
    <div class="clear"></div>
  </div>
<% else %>
  <h1>Got a problem? Solve it.<br/>
    <small>Create a series of questions to help solve your problem by rating each possible solution.</small>
  </h1>
  <%= link_to "Sign up now!", new_user_registration_path, :class => "btn large success" %>
<% end %>