config/routes.rb
Ranker::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  resources :problems do
    member do
      put 'questions'
      get 'copy'
    end
    resources :questions, :only => [ :create ]
    resources :solutions, :only => [ :new, :create ]
  end
  resources :solutions, :except => [ :index, :new, :create ] do
    member do
      put 'answers'
    end
    resources :answers, :only => [ :create ]
  end
  resources :answers, :only => [ :update ]
  resources :questions, :only => [ :update, :destroy ]

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

  match '/error', :to => 'pages#error', :as => 'error'
  match '*a', :to => 'pages#error'

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  attr_accessible :name, :comment, :answers_attributes

  belongs_to :problem
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers, :allow_destroy => true

  validates :name, :presence => true,
                   :length => { :maximum => 75 },
                   :uniqueness => { :scope => :problem_id }
  validates :problem_id, :presence => true

  default_scope :order => 'solutions.completed DESC, solutions.answer_total DESC'

  def update_answers(answers)
    errors = {}
    answers.each do |index, answer_attrs|
      answer = self.answers.find_by_id(answer_attrs["id"])
      if answer.blank? and not answer = self.answers.find_by_question_id(answer_attrs["question_id"])
        #TODO - should this error, or can we handle it somehow?
        self.answers.create!(answer_attrs)
      else
        unless answer.update_attributes(answer_attrs)
          errors[answer_attrs["id"]] = answer.errors
        end
      end
    end
    errors
  end

  def update_answer_total
    #When the rating is nil, it will convert to the integer zero
    self.answer_total = self.answers.collect{ |i| i.rating.to_i * i.question.weight.to_i }.sum
    self.save!
  end

  def validate_solution
    if self.problem.questions.length > self.answers.length
      self.completed = false
    elsif answers.find_by_rating(nil)
      self.completed = false
    else
      self.completed = true
    end
    self.save!
  end

  def match_decimal
    questions = self.problem.questions
    0 if questions.empty?

    if questions.length > self.answers.length
      # Not all questions have been answered
      -1
    elsif self.answers.find_by_rating(nil)
      # Not all questions have been answered
      -1
    else
      self.answer_total.to_f / self.problem.question_potential
    end
  end

  def answers_without_category
    answers_by_category_id(nil)
  end

  def answers_by_category_id(id)
    questions = self.problem.questions.find_all_by_category_id(id)
    if (questions.blank?)
      []
    end

    answers = []
    questions.each do |question|
      answer = self.answers.find_by_question_id(question.id)
      unless answer.blank?
        answers << answer
      end
    end
    answers
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_problem, :only => [:new, :create]
  before_filter :load_solution, :except => [:new, :create]

  def new
    @solution = @problem.solutions.new
    @title = "New solution"
  end

  def create
    @solution = @problem.solutions.build(params[:solution])
    if @solution.save
      redirect_to @solution, :flash => { :success => "Solution created!" }
    else
      render :new
    end
  end

  def destroy
    name = @solution.name
    if @solution.destroy
      redirect_to problem_path(@problem), :flash => { :success => "#{name} deleted" }
    else
      redirect_to @solution, :flash => { :failure => "Error deleting solution"}
    end
  end

  def show
    @title = @solution.name

    @questions = @solution.problem.questions

    unless @questions.nil?
      @questions.each do |question|
        unless @solution.answers.find_by_question_id(question.id)
          @solution.answers.create!(:question_id => question.id)
        end
      end
    end

    # sort doesn't do anything for the form since the form is unsorted
    @answers = @solution.answers.sort_by {|answer| answer.question.position}
  end

  def edit
    @title = "Edit solution"
  end

  def update
    if @solution.update_attributes(params[:solution])
      redirect_to @solution, :flash => { :success => "Solution updated." }
    else
      @title = "Edit solution"
      render :edit
    end
  end

  def answers
    success = @solution.update_attributes(params[:solution])
    if success
      redirect_to @problem, :flash => { :success => "Answers updated." }
    else
      @title = @solution.name
      @questions = @solution.problem.questions
      #TODO - don't think this is right
      @answers = params[:solution]
      render :show
    end
  end

  private

    def load_problem
      begin
        @problem = current_user.problems.find(params[:problem_id])
      rescue
        redirect_to error_path, :flash => { :failure => "Problem does not exist" }
      end
    end

    def load_solution
      begin
        if @problem.nil?
          @solution = Solution.find(params[:id])
          @problem = @solution.problem
          redirect_to error_path, :flash => { :failure => "Solution does not exist" } unless @problem.user_id == current_user.id
        else
          @solution = @problem.solutions.find(params[:id])
        end
      rescue
        redirect_to error_path, :flash => { :failure => "Solution does not exist" }
      end
    end

end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/_answer_fields.html.erb
<li class="well answer">
  <div class="left field">
    <%= f.label :rating, f.object.question.text %>
    <%= f.radio_button :rating, 1 %>&nbsp;1
    <%= f.radio_button :rating, 2 %>&nbsp;2
    <%= f.radio_button :rating, 3 %>&nbsp;3
    <%= f.radio_button :rating, 4 %>&nbsp;4
    <%= f.radio_button :rating, 5 %>&nbsp;5
  </div>
    <div class="right field">
      <%= f.label :comment %>
      <%= f.text_area :comment, :id => "comment_#{f.object.id}", :class => "span6" %>
    </div>
  <%= f.hidden_field :question_id %>
  <div class="clear"></div>
</li>

app/views/solutions/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
  <li><%= link_to @problem.name, @problem %><span class="divider">/</span></li>
  <li><%= link_to @solution.name, @solution %><span class="divider">/</span></li>
  <li class="active">Edit</li>
</ul>

<%= form_for @solution, :html => {:class => "form-stacked"} do |f| %>
  <h2>Edit solution</h2>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
	<%= f.text_field :name, :class => "span6" %>
  </div>
  <div class="field">
    <%= f.label :comment %>
	<%= f.text_area :comment, :class => "span6" %>
  </div>
  <%= f.hidden_field :problem_id, :value => @problem.id %>
  <div class="well">
	<%= f.submit "Update", :class => "btn large primary span2" %>
    <%= link_to "Delete", solution_path(@solution), :class => "btn large danger", :confirm => "Are you sure?", :method => :delete %>
  </div>

<% end %>

app/views/solutions/new.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
  <li><%= link_to @problem.name, @problem %><span class="divider">/</span></li>
  <li class="active">New Solution</li>
</ul>

<%= form_for [@problem, @solution], :html => {:class => "form-stacked"} do |f| %>
  <h2>New solution for <%= link_to @problem.name, @problem %></h2>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
	<%= f.text_field :name, :class => "span6" %>
  </div>
  <div class="field">
    <%= f.label :comment %>
	<%= f.text_area :comment, :class => "span6" %>
  </div>
  <div class="well">
	<%= f.submit "Create", :class => "btn large primary span2" %>
    <%= link_to "Cancel", problem_path(@problem), :class => "btn large danger" %>
  </div>
<% end %>

app/views/solutions/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
  <li><%= link_to @problem.name, @problem %><span class="divider">/</span></li>
  <li class="active"><%= @solution.name %></li>
</ul>

  <h1><%= @solution.name %>&nbsp;<small><%= link_to "Edit", edit_solution_path(@solution) %></small>
  <% unless @solution.comment.blank? %>
  <small><%= simple_format(@solution.comment) %></small>
  <% end %>
  </h1>



  <% unless @solution.problem.questions.blank? %>
      <%= form_for @solution, :url => {:action => 'answers'}, :html => {:class => "form-stacked"}, :method => :put do |f| %>
        <% unless @solution.problem.categories.blank? %>
           <% @solution.problem.categories.each do |category| %>
              <% unless @solution.answers_by_category_id(category.id).empty? %>
                  <div class="category-section round">
                      <h3><%= category.name %>&nbsp;<span class="btn toggle-category" id="category_<%=category.id%>">Hide</span></h3>
                      <ul class="answers" id="answers_category_<%=category.id%>">
                          <%= f.fields_for :answers, @solution.answers_by_category_id(category.id).sort_by {|answer| answer.question.position} do |builder| %>
                            <%= render 'shared/error_messages', :object => builder.object %>
                            <%= render "answer_fields", :f => builder %>
                          <% end %>
                      </ul>
                  </div>
              <% end %>
           <% end %>
        <% end %>
        <% unless @solution.answers_by_category_id(nil).blank? %>
           <div class="category-section round">
               <h3>Uncategorized</span>&nbsp;<span class="btn toggle-category" id="category_none">Hide</span></h3>
               <ul class="answers" id="answers_category_none">
                   <%= f.fields_for :answers, @solution.answers_without_category.sort_by {|answer| answer.question.position} do |builder| %>
                      <%= render 'shared/error_messages', :object => builder.object %>
                      <%= render "answer_fields", :f => builder %>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div class="well">
	        <%= f.submit "Update", :class => "btn large primary span2" %>
            <%= link_to "Cancel", solution_path(@solution), :class => "btn large danger" %>
        </div>
      <% end %>
    <% if @answers.empty? %>
      No questions exist. Create questions <%= link_to "here", problem_questions_path(@problem) %>
    <% end %>
  <% end %>

          <script type="text/javascript">
            $('.toggle-category').click(function() {
                $("#answers_" + this.id).slideToggle('normal', function() {
                // Animation complete.
                var $header = $("#" + this.id.substring(8));

                if ($header.text().trim() == "Hide") {
                  $header.text("Show");
                } else {
                  $header.text("Hide");
                }
              });
            });
          </script>