config/routes.rb
Ranker::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  resources :problems do
    member do
      put 'questions'
      get 'copy'
    end
    resources :questions, :only => [ :create ]
    resources :solutions, :only => [ :new, :create ]
  end
  resources :solutions, :except => [ :index, :new, :create ] do
    member do
      put 'answers'
    end
    resources :answers, :only => [ :create ]
  end
  resources :answers, :only => [ :update ]
  resources :questions, :only => [ :update, :destroy ]

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

  match '/error', :to => 'pages#error', :as => 'error'
  match '*a', :to => 'pages#error'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div>
      <p>Built by <a href="http://twitter.com/br0nc080" target="_blank">@br0nc080</a></p>
      <p>Any questions or comments appreciated.</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <%= link_to logo, root_path %>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'application' %>

app/views/layouts/_topbar.html.erb
<div class="topbar" data-scrollspy="scrollspy">
  <div class="topbar-inner">
    <div class="container">
      <%= link_to "Residency Ranker", root_path, :class => "brand" %>
      <ul class="nav">
      </ul>
      <ul class="nav secondary-nav">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Edit Profile", edit_user_registration_path %>
        </li>
        <% end %>
        <li>
          <%= link_to "Help", help_path %>
        </li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
    //google analytics
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-25054049-4']);
    _gaq.push(['_trackPageview']);

    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body>
  <%= render 'layouts/topbar' %>
  <%= render 'layouts/header' %>
  <div class="container">
	<section class="round">
	  <% flash.each do |key, value| %>
		<%= content_tag(:div, value, :class => "flash #{key}") %>
	  <% end %>
	  <%= yield %>
	</section>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>